# Dependencies
markdown:             kramdown
highlighter:          rouge

# Permalinks
permalink:            pretty

# Setup
title:                Fredrik Averpil
tagline:              My personal blog
description:          My personal blog – on Python development, 3D graphics, compositing and photography.
url:                  https://fredrikaverpil.github.io
baseurl:              /
paginate:             5
gems:                 [jekyll-paginate, jekyll-gist] # not used ad the moment
author:
  name:               Fredrik Averpil
  twitter_url:        https://twitter.com/fredrikaverpil
  twitter_username:   fredrikaverpil
  github_repo:        https://github.com/fredrikaverpil/fredrikaverpil.github.io

# Custom vars
custom_pages:
  feed:               /atom.xml
excerpt_separator:    <!--more-->
google_analytics:     UA-70773524-1
hyde_version:         2.1.0
hyde_url:             http://hyde.getpoole.com
hyde_repo:            https://github.com/poole/hyde
show_related_posts:   false
force_https:          true

# Comments
comments:
  use_disqus:         true
  use_googleplus:     false
  use_livefyre:       false
  disqus_shortname:   ffredrikk
  livefyre_siteid:    379699
