# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Fredrik Averpil
tagline:          My personal blog
description:      My personal blog – on Python development, 3D graphics, compositing and photography.
url:              http://fredrikaverpil.github.io
baseurl:          /

author:
  name:           Fredrik Averpil
  url:            https://twitter.com/fredrikaverpil
  repo:           https://github.com/fredrikaverpil/fredrikaverpil.github.io


paginate:         5

# Custom vars
hyde_version:     2.1.0
hyde_url:         http://hyde.getpoole.com
hyde_repo:        https://github.com/poole/hyde

excerpt_separator: <!--more-->

pages_list:
  title:           /atom.xml

disqus_shortname: ffredrikk
google_analytics: UA-70773524-1
